source 'https://github.com/CocoaPods/Specs.git'
pod 'MBProgressHUD', '~> 0.9'
pod 'Reachability', '~> 3.2'
pod 'AFNetworking', '~> 2.4.1'
pod 'SDWebImage', '~> 3.7.0'
pod 'MHTextField', '~> 0.5'
pod 'EaseMobSDK', '~> 2.1.0'
pod 'MSPullToRefreshController', '~> 1.1.0'
pod 'UITableView-NXEmptyView', '~> 0.1.7'
pod 'ZCSAvatarCapture', '~> 0.0.4'
pod 'ELCImagePickerController', '~> 0.2.0'
pod 'SlimeRefresh', '~> 0.0.1'
pod 'THProgressView', '~> 1.0'
pod 'MWPhotoBrowser', '~> 1.4.1'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'WCAlertView', '~> 1.0.1'
pod 'SZTextView', '~> 1.1.10'